main: p3_student.o p3_student.h p3_student_list.o p3_student_list.h
	gcc -o pool3 main.c p3_student.o p3_student_list.o
p3_student.o: p3_student.c p3_student.h
	gcc -c p3_student.c
p3_student_list.o: p3_student_list.c p3_student_list.h
	gcc -c p3_student_list.c
